version: 2
updates:
  # npm 패키지 의존성 업데이트 설정
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # 개발 브랜치에 PR 생성
    target-branch: "master"
    # 보안 업데이트 우선 활성화
    open-pull-requests-limit: 15
    # 보안 이슈 우선순위
    labels:
      - "dependencies"
      - "security"
    # PR에서 무시할 의존성 패턴
    ignore:
      # 메이저 버전은 수동 업데이트
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # 취약점 자동 검사 및 PR 생성
    security-updates-only: false
    # 자동 병합 설정 활성화
    assignees:
      - "dependabot"
    reviewers:
      - "DanjiTalk/security-team"
    # 낮은 취약점도 업데이트 (CVE가 발행된 모든 취약점)
    vulnerabilities:
      - severity: "low"
        update-types: ["security:vulnerability"]
      - severity: "medium"
        update-types: ["security:vulnerability"]
      - severity: "high"
        update-types: ["security:vulnerability"]
      - severity: "critical"
        update-types: ["security:vulnerability"]

  # GitHub Actions 업데이트 설정
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels:
      - "dependencies"
      - "github-actions"
    # 자동 병합 설정 활성화
    assignees:
      - "dependabot"
    reviewers:
      - "DanjiTalk/security-team" 