name: 릴리스 생성

on:
  push:
    tags:
      - 'v*'  # 'v'로 시작하는 태그가 푸시될 때 트리거

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2
        
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 종속성 설치
        run: npm install
        working-directory: ./

      - name: 릴리스 생성
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/**'
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## 개요
            새로운 기능과 버그 수정이 포함된 릴리스입니다.
          discussion_category_name: 'General'

      - name: 릴리스 URL 출력
        run: |
          echo 릴리스 생성: ${{ steps.release.outputs.html_url }}
